GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/65bbccb6215e0667cd60f47a

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Ahsan",
    "subscribedToChannel": "Web Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/65bb5ad733601ec5a8107d13